Add channel_simple query to live endpoint
holofans/holoapi pull request #63
Opened 2020-08-25 14:42 UTC by Choooks22

2020-08-25 14:48 UTC, IAmVisco requested changes

2020-08-25 14:48 UTC, IAmVisco commented on apps/api-doc/swagger.yaml
> +            as a bandwidth saving measure. Cannot be used with `channel_simple`.
Adjust docs models too.

2020-08-25 14:48 UTC, IAmVisco commented on apps/client-api/routes/v1/live.js
> +  if (+channel_simple && +hide_channel_desc) {
No need to convert them - this may lead to errors (0 && 0). Just check their existence.

2020-10-18 23:52 UTC, merged

2020-10-18 23:53 UTC, sphinxrave commented
I set up a new PR and merged it 👍