V2 DB Migration & Backwards Compatibility
holofans/holoapi pull request #68
Opened 2020-10-12 05:38 UTC by sphinxrave

This PR does a few things:
1. Upgrades database to make it ready for V2
2. Adds `organization` and `group` column to channels table, and marks existing channels as "Hololive" organization
3. Isolates V1 endpoints by adding Hololive organization filter whereever there is a search (/live, /channels, /video). I ignored comments API purposefully as it's a bit expensive to add channel filtering ability.
4. Moves API docs to v1/api-docs and chained redirects.
5. Moved constants around to make versioning a bit easier.

2020-10-18 10:15 UTC, IAmVisco requested changes

2020-10-18 10:15 UTC, IAmVisco commented on consts/index.js
> +  HOLOLIVE: 'Hololive',
I will nitpick and say that official stylizing is `hololive`.

2020-10-18 10:15 UTC, IAmVisco commented on consts/v1_consts.js
> +exports.RESPONSE_FIELDS = {
I don't like that `v1` file name. At the very least make it `v1Consts`. And perhaps don't split consts by route version - I can see those fields being reused in v2 and onwards. Maybe.

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +    const { DataTypes } = Sequelize;
You don't need to do that. That `Sequelize` param exposes `DataTypes` directly and some even rename it to `DataTypes`.

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +        type: DataTypes.INTEGER,
Probably won't fit.

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      discord_name: DataTypes.STRING,
Do we need it? It can be updated easily but DB will have old data 🤔

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      is_admin: DataTypes.BOOLEAN,
Why is there a field named `is_admin` in `admin` table?

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      granted_by: DataTypes.INTEGER,
Place timestamps last, after all the user fields.

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      granted_by: DataTypes.INTEGER,
Missing FK?

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +        },
onDelete behavior? It defaults to `RESTRICT`.

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      start: DataTypes.INTEGER,
Start of what?

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      duration: DataTypes.INTEGER,
I see no use in that field.

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      contributor_id: DataTypes.INTEGER,
Again, move timestamps to the end, missing FK for the contributor.

2020-10-18 10:15 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +    await queryInterface.createTable(TABLES.GAME, {
As discussed before on Discord, should be one-to-many game-to-video.

2020-10-18 10:15 UTC, IAmVisco commented on database/models/game.js
> +    this.contributor = this.belongsTo(models.Admin, { as: 'contributor', foreignKey: 'contributor_id' });
Those associations won't be applied in migration since you didn't write them there.

2020-10-18 23:55 UTC, sphinxrave commented on consts/v1_consts.js
> +exports.RESPONSE_FIELDS = {
I was thinking if we want something consistent across all routes, we throw it in consts.js, but if it's static to v1, then we immortalize it in v1_consts.js to prevent change pollution.

2020-10-18 23:55 UTC, sphinxrave commented on database/migrations/20201011065904-v2-db.js
> +      is_admin: DataTypes.BOOLEAN,
should've named the table 'curators'

2020-10-18 23:56 UTC, sphinxrave commented on database/migrations/20201011065904-v2-db.js
> +        },
will have to investigate, good call-out!

2020-10-24 01:29 UTC, sphinxrave commented
![image](https://user-images.githubusercontent.com/62570796/97064812-b81d4580-155d-11eb-925a-2a869289011f.png)

2020-10-24 01:33 UTC, sphinxrave commented
```Table "channel" {
  "id" integer [not null]
  "yt_channel_id" "character varying(255)"
  "yt_uploads_id" "character varying(255)"
  "bb_space_id" integer
  "bb_room_id" integer
  "name" "character varying(255)"
  "description" text
  "photo" text
  "published_at" timestamp
  "status" "character varying(255)" [not null]
  "twitter_link" "character varying(255)"
  "facebook_link" "character varying(255)"
  "twitch_link" "character varying(255)"
  "instagram_link" "character varying(255)"
  "crawled_at" timestamp
  "created_at" timestamp
  "updated_at" timestamp
  "comments_crawled_at" timestamp
  "view_count" integer
  "subscriber_count" integer
  "video_count" integer
  "organization" "character varying(255)"
  "group" "character varying(255)"

Indexes {
  name [type: btree, name: "channel_name"]
}
}

Table "channel_stats" {
  "id" integer [not null, default: `nextval('public.channel_stats_id_seq'::regclass)`]
  "channel_id" integer [not null]
  "yt_views" integer
  "yt_subscribers" integer
  "bb_followers" integer
  "created_at" timestamp
  "updated_at" timestamp
}

Table "curator" {
  "discord_id" bigint [not null]
  "discord_name" "character varying(255)"
  "is_admin" boolean
  "is_editor" boolean
  "granted_by" bigint
  "created_at" timestamp
  "updated_at" timestamp
}

Table "game" {
  "id" "character varying(255)" [not null]
  "name" "character varying(255)"
  "created_at" timestamp
  "updated_at" timestamp
}

Table "song" {
  "id" integer [not null]
  "video_id" integer [not null]
  "start" integer
  "duration" integer
  "name" "character varying(255)"
  "contributor_id" bigint [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "video" {
  "id" integer [not null]
  "channel_id" integer [not null]
  "yt_video_key" "character varying(11)"
  "bb_video_id" "character varying(11)"
  "title" "character varying(255)"
  "description" text
  "thumbnail" text
  "published_at" timestamp
  "status" "character varying(255)" [not null]
  "live_schedule" timestamp
  "live_start" timestamp
  "live_end" timestamp
  "live_viewers" integer
  "is_uploaded" boolean
  "late_secs" integer
  "duration_secs" integer
  "is_captioned" boolean
  "is_licensed" boolean
  "is_embeddable" boolean
  "created_at" timestamp
  "updated_at" timestamp
  "game_id" "character varying(255)"

Indexes {
  title [type: btree, name: "video_title"]
}
}

Table "video_comment" {
  "id" integer [not null]
  "video_id" integer [not null]
  "message" text
  "created_at" timestamp
  "updated_at" timestamp
  "comment_key" "character varying(255)" [not null]

Indexes {
  video_id [type: btree, name: "video_comment_video_id"]
}
}

Ref:"channel"."id" < "channel_stats"."channel_id" [delete: cascade]

Ref:"curator"."discord_id" < "curator"."granted_by" [delete: cascade]

Ref:"curator"."discord_id" < "song"."contributor_id" [delete: cascade]

Ref:"video"."id" < "song"."video_id" [delete: cascade]

Ref:"channel"."id" < "video"."channel_id" [delete: cascade]

Ref:"video"."id" < "video_comment"."video_id" [delete: cascade]

Ref:"game"."id" < "video"."game_id" [delete: set null]
```

2020-10-24 01:40 UTC, sphinxrave commented on database/migrations/20201011065904-v2-db.js
> +      start: DataTypes.INTEGER,
it's a more formalized version of video_comment, so start is seconds from start of video

2020-10-24 01:40 UTC, sphinxrave commented on database/migrations/20201011065904-v2-db.js
> +      duration: DataTypes.INTEGER,
duration describes how long the song is in seconds

2020-10-25 12:31 UTC, IAmVisco requested changes

2020-10-25 12:31 UTC, IAmVisco commented on database/migrations/20201011065904-v2-db.js
> +      is_admin: Sequelize.BOOLEAN,
Wanna try making `Role` and `CuratorRole` m2m tables? Not sure if this overkill or planning for future expansion.

2020-10-25 12:31 UTC, IAmVisco commented on database/models/curator.js
> +      foreignKey: 'discord_id' });
Not sure what happened with formatting on this line.

2020-10-25 12:31 UTC, IAmVisco commented on database/models/song.js
> +          onDelete: 'cascade',
It doesn't matter but since it's direct SQL instruction, write it out in caps.

2020-10-25 12:31 UTC, IAmVisco commented on database/models/game.js
> +        name: DataTypes.STRING,
Feels empty. Maybe add `image` or something 🤔

2020-10-26 00:31 UTC, sphinxrave commented on database/migrations/20201011065904-v2-db.js
> +      is_admin: Sequelize.BOOLEAN,
probably overkill, we can adopt it later if it comes in necessary

2020-10-26 10:31 UTC, IAmVisco approved these changes

2020-10-30 07:20 UTC, merged