Auto refresh live every 15 seconds
holofans/holoapi pull request #80
Opened 2020-12-05 07:47 UTC by sphinxrave

2020-12-05 10:10 UTC, IAmVisco requested changes

2020-12-05 10:10 UTC, IAmVisco commented on apps/client-api/services/CacheService.js
> +  async getStringFromCache(key) {
But why

2020-12-05 10:10 UTC, IAmVisco commented on apps/client-api/routes/v1/util/live.js
> +const { Op } = require('sequelize');
I see why you moved it but file path kinda looks weird. Maybe a service or something.

2020-12-07 23:58 UTC, dragonjet commented on apps/crawler-youtube/tasks/live-cache-update.js
> +};
he probably wants to move execution to next process without waiting for the first block's `await computeLive`. could probably function it and `Promise.all` both calls, but I'm also fine with current, doesn't hurt.

2020-12-08 06:25 UTC, sphinxrave commented on apps/client-api/services/CacheService.js
> +  async getStringFromCache(key) {
grabbing this live JSON and deserializing it is completely useless.

2020-12-08 11:33 UTC, sphinxrave commented on apps/client-api/routes/v1/live.js
> +    return res.end(cache);
res.json you have to give it a json object (which it stringifies) instead i give it a string and handle the header myself. faster this way.

2020-12-08 11:34 UTC, sphinxrave commented on apps/client-api/routes/v1/util/live.js
> +const { Op } = require('sequelize');
let's just keep it here for now, some refactoring work required for v2 anyway

2020-12-08 11:43 UTC, merged